### ISSUE TITLE
Some network interfaces does not listed

### ISSUE THREAD

**Issue by helioguardabaxo** [f18m/cmonitor#7] opened 2021-05-13 00:35 UTC
Hi, @f18m !
I am trying to collect traffic in network created in Mininet but some interfaces does not listed in cmonitor. Just some switches are listed as interfaces. 
![image](https://user-images.githubusercontent.com/24301085/118060381-0c0c4200-b369-11eb-930c-f35932c702e0.png)

I check on Wireshark and its ok.
![image](https://user-images.githubusercontent.com/24301085/118060224-9ef8ac80-b368-11eb-9dfd-406a081669fc.png)
This interface is capturing traffic:
![image](https://user-images.githubusercontent.com/24301085/118060307-dff0c100-b368-11eb-8297-ab029b3b4d94.png)

My network looks like this:
![image](https://user-images.githubusercontent.com/24301085/118060769-ec294e00-b369-11eb-8871-12006ed97b04.png)

are there any limitations on the number of interfaces?
Thanks!

**Comment by f18m** [comment] 2021-05-15 21:44
Hi @helioguardabaxo ,
no there's no explicit limit on the number of interfaces monitored. 
You can check by inspecting the function CMonitorCollectorApp::proc_net_dev().

However the interfaces monitored by cmonitor are the ones found via "/sbin/ifconfig -s".
Can you check if the interfaces you do not find in cmonitor output appear in "/sbin/ifconfig -s" output?

**Comment by f18m** [comment] 2022-01-04 01:20
Hi @helioguardabaxo ,
the code to list network interfaces in cmonitor_collector has been just changed to avoid use of "ifconfig" utility: this makes it easier to check which criteria are used to list interfaces.

Also re-reading the bug description and looking at screenshots I wonder: did you check if "switch1-eth3" did appear inside the .JSON file produced by cmonitor_collector?

Anyway I'm closing this bug for now as I cannot reproduce it and got no feedback in last 7 months...please reopen it if you still find the problem with version 2.2, thanks.

**Closed by f18m** 2022-01-04 01:20 UTC
Labels: question
